/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Cadastro;

import Controller.ControleCliente;
import Controller.ControleVenda;
import View.Pesquisa.PesquisaCliente;
import View.Pesquisa.PesquisaProduto;
import View.Pesquisa.PesquisaUsuario;
import View.Pesquisa.PesquisaVenda;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Luan
 */
public class CadastroVenda extends javax.swing.JFrame {
    SelecionarCliente selCli;
    SelecionarProduto selProd ;
    boolean config =false;
    Carrinho carrinho;
    ControleCliente controlCliente = new ControleCliente();
    ControleVenda controlVenda = new ControleVenda();
    int op=0, cont=0;
    int idClient =-1, idProd = -1, qtd, idvenda =-1 ;
    String [] colunas = new String[]{"Id de Venda","NOME DO PRODUTO","DESCRIÇÃO","PREÇO", "QUANTIDADE","PREÇO TOTAL"};
    /**
     * Creates new form CadastroVenda
     */
    public CadastroVenda(boolean config) {
        
        initComponents();
        this.config = config;
        btnIrCarrinho.setEnabled(false);
       
      //  op = openCliente();
        
        
    }
    public CadastroVenda(int idclient ,int idvenda, boolean config){
        initComponents();
        btnIrCarrinho.setEnabled(true);
        this.idvenda = idvenda;
        idClient = idclient;
        openProduto();
        selProd.lblIdCli.setText(String.valueOf(idClient));
        //atualizar tabela do carrinho
        selProd.tabCarrinho = uptabela(selProd.tabCarrinho, idvenda) ;
       
        this.config = config;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPane = new javax.swing.JDesktopPane();
        btnSelCliente = new javax.swing.JButton();
        btnSelProd = new javax.swing.JButton();
        btnAvancar = new javax.swing.JButton();
        btnAddCarrinho = new javax.swing.JButton();
        btnIrCarrinho = new javax.swing.JButton();
        btnExcluirCarrinho = new javax.swing.JButton();
        btnRegistrarVenda = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();
        menuBarra = new javax.swing.JMenuBar();
        jMenuCliente = new javax.swing.JMenu();
        menuClieCad = new javax.swing.JMenuItem();
        menuCliePesq = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        menuUser = new javax.swing.JMenu();
        menuUserCad = new javax.swing.JMenuItem();
        menuUserPesq = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        menuProdCad = new javax.swing.JMenuItem();
        menuProdPesq = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenu();
        menuVendCad = new javax.swing.JMenuItem();
        menuVendPesq = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        relatorioMenuCliente = new javax.swing.JMenu();
        exportClientePDF = new javax.swing.JMenuItem();
        exportVisuRelatorioClientes = new javax.swing.JMenuItem();
        exportMaioresClientes = new javax.swing.JMenuItem();
        relatorioMenuProduto = new javax.swing.JMenu();
        exportProdutoPDF = new javax.swing.JMenuItem();
        exportVisuRelatorioProdutos = new javax.swing.JMenuItem();
        relatorioMenuVenda = new javax.swing.JMenu();
        exportVendasPDF = new javax.swing.JMenuItem();
        exportVisuRelatorioVenda = new javax.swing.JMenuItem();
        exportVisuVendasAgrupadas = new javax.swing.JMenuItem();
        exportVendasAgrupadasPDF = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(deskPane);
        deskPane.setBounds(170, 30, 980, 650);

        btnSelCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSelCliente.setText("Selecionar Cliente");
        btnSelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelCliente);
        btnSelCliente.setBounds(10, 40, 150, 40);

        btnSelProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSelProd.setText("Selecionar Produto");
        btnSelProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelProd);
        btnSelProd.setBounds(10, 90, 150, 40);

        btnAvancar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvancar);
        btnAvancar.setBounds(10, 160, 150, 40);

        btnAddCarrinho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddCarrinho.setText("Adicionar à Sacola");
        btnAddCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarrinhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCarrinho);
        btnAddCarrinho.setBounds(10, 210, 150, 40);

        btnIrCarrinho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIrCarrinho.setText("Ir ao Carrinho");
        btnIrCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrCarrinhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnIrCarrinho);
        btnIrCarrinho.setBounds(10, 270, 150, 40);

        btnExcluirCarrinho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirCarrinho.setText("Excluir Produto");
        btnExcluirCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCarrinhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluirCarrinho);
        btnExcluirCarrinho.setBounds(10, 390, 150, 40);

        btnRegistrarVenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarVenda.setText("Registrar Venda");
        btnRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarVenda);
        btnRegistrarVenda.setBounds(10, 560, 150, 40);

        lblFundo.setBackground(new java.awt.Color(0, 255, 255));
        lblFundo.setMaximumSize(new java.awt.Dimension(1400, 800));
        lblFundo.setName(""); // NOI18N
        lblFundo.setOpaque(true);
        lblFundo.setPreferredSize(new java.awt.Dimension(980, 580));
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1210, 780);

        jMenuCliente.setText("Cliente");

        menuClieCad.setText("Cadastrar");
        menuClieCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClieCadActionPerformed(evt);
            }
        });
        jMenuCliente.add(menuClieCad);

        menuCliePesq.setText("Pesquisar");
        menuCliePesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCliePesqActionPerformed(evt);
            }
        });
        jMenuCliente.add(menuCliePesq);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemSair);

        menuBarra.add(jMenuCliente);

        menuUser.setText("Usuario");

        menuUserCad.setText("Cadastrar");
        menuUserCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserCadActionPerformed(evt);
            }
        });
        menuUser.add(menuUserCad);

        menuUserPesq.setText("Pesquisar");
        menuUserPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserPesqActionPerformed(evt);
            }
        });
        menuUser.add(menuUserPesq);

        menuBarra.add(menuUser);

        menuProduto.setText("Produto");

        menuProdCad.setText("Cadastrar");
        menuProdCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdCadActionPerformed(evt);
            }
        });
        menuProduto.add(menuProdCad);

        menuProdPesq.setText("Pesquisar");
        menuProdPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdPesqActionPerformed(evt);
            }
        });
        menuProduto.add(menuProdPesq);

        menuBarra.add(menuProduto);

        menuVenda.setText("Venda");

        menuVendCad.setText("Cadastrar");
        menuVendCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendCadActionPerformed(evt);
            }
        });
        menuVenda.add(menuVendCad);

        menuVendPesq.setText("Pesquisar");
        menuVendPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendPesqActionPerformed(evt);
            }
        });
        menuVenda.add(menuVendPesq);

        menuBarra.add(menuVenda);

        menuRelatorios.setText("Relatórios");

        relatorioMenuCliente.setText("Cliente");

        exportClientePDF.setText("Exportar para PDF");
        exportClientePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportClientePDFActionPerformed(evt);
            }
        });
        relatorioMenuCliente.add(exportClientePDF);

        exportVisuRelatorioClientes.setText("Visualizar Relatórios Clientes");
        exportVisuRelatorioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportVisuRelatorioClientesActionPerformed(evt);
            }
        });
        relatorioMenuCliente.add(exportVisuRelatorioClientes);

        exportMaioresClientes.setText("Maiores Clientes");
        exportMaioresClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportMaioresClientesActionPerformed(evt);
            }
        });
        relatorioMenuCliente.add(exportMaioresClientes);

        menuRelatorios.add(relatorioMenuCliente);

        relatorioMenuProduto.setText("Produto");

        exportProdutoPDF.setText("Exportar para PDF");
        exportProdutoPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportProdutoPDFActionPerformed(evt);
            }
        });
        relatorioMenuProduto.add(exportProdutoPDF);

        exportVisuRelatorioProdutos.setText("Visualizar Relatório Produtos");
        exportVisuRelatorioProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportVisuRelatorioProdutosActionPerformed(evt);
            }
        });
        relatorioMenuProduto.add(exportVisuRelatorioProdutos);

        menuRelatorios.add(relatorioMenuProduto);

        relatorioMenuVenda.setText("Venda");

        exportVendasPDF.setText("Exportar para PDF");
        exportVendasPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportVendasPDFActionPerformed(evt);
            }
        });
        relatorioMenuVenda.add(exportVendasPDF);

        exportVisuRelatorioVenda.setText("Visualizar Relatório de Venda");
        exportVisuRelatorioVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportVisuRelatorioVendaActionPerformed(evt);
            }
        });
        relatorioMenuVenda.add(exportVisuRelatorioVenda);

        exportVisuVendasAgrupadas.setText("Vendas Agrupadas Visualização");
        exportVisuVendasAgrupadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportVisuVendasAgrupadasActionPerformed(evt);
            }
        });
        relatorioMenuVenda.add(exportVisuVendasAgrupadas);

        exportVendasAgrupadasPDF.setText("Vendas Agrupadas Exportar PDF");
        exportVendasAgrupadasPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportVendasAgrupadasPDFActionPerformed(evt);
            }
        });
        relatorioMenuVenda.add(exportVendasAgrupadasPDF);

        menuRelatorios.add(relatorioMenuVenda);

        menuBarra.add(menuRelatorios);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        menuBarra.add(jMenuSair);

        setJMenuBar(menuBarra);

        setSize(new java.awt.Dimension(1216, 839));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuClieCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClieCadActionPerformed
        CadastroCliente obj_acesso = new CadastroCliente();
        obj_acesso.setVisible(true);
    }//GEN-LAST:event_menuClieCadActionPerformed

    private void menuCliePesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCliePesqActionPerformed
        PesquisaCliente obj_acesso = new PesquisaCliente();
        obj_acesso.setVisible(true);
    }//GEN-LAST:event_menuCliePesqActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void menuUserCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserCadActionPerformed
        CadastroUsuario obj = new CadastroUsuario();
        obj.setVisible(true);
    }//GEN-LAST:event_menuUserCadActionPerformed

    private void menuUserPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserPesqActionPerformed
        PesquisaUsuario obj = new PesquisaUsuario();
        obj.setVisible(true);
    }//GEN-LAST:event_menuUserPesqActionPerformed

    private void menuProdCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdCadActionPerformed
        CadastroProduto obj_acesso = new CadastroProduto();
        obj_acesso.setVisible(true);
    }//GEN-LAST:event_menuProdCadActionPerformed

    private void menuProdPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdPesqActionPerformed
        PesquisaProduto obj_acesso = new PesquisaProduto();
        obj_acesso.setVisible(true);
    }//GEN-LAST:event_menuProdPesqActionPerformed

    private void menuVendCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendCadActionPerformed
        CadastroVenda obj_acesso = new CadastroVenda(false);
        obj_acesso.setVisible(true);
    }//GEN-LAST:event_menuVendCadActionPerformed

    private void menuVendPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendPesqActionPerformed
        PesquisaVenda obj_acesso = new PesquisaVenda();
        obj_acesso.setVisible(true);
    }//GEN-LAST:event_menuVendPesqActionPerformed

    private void exportClientePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportClientePDFActionPerformed

    }//GEN-LAST:event_exportClientePDFActionPerformed

    private void exportVisuRelatorioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportVisuRelatorioClientesActionPerformed

    }//GEN-LAST:event_exportVisuRelatorioClientesActionPerformed

    private void exportMaioresClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportMaioresClientesActionPerformed

    }//GEN-LAST:event_exportMaioresClientesActionPerformed

    private void exportProdutoPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportProdutoPDFActionPerformed

    }//GEN-LAST:event_exportProdutoPDFActionPerformed

    private void exportVisuRelatorioProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportVisuRelatorioProdutosActionPerformed

    }//GEN-LAST:event_exportVisuRelatorioProdutosActionPerformed

    private void exportVendasPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportVendasPDFActionPerformed

    }//GEN-LAST:event_exportVendasPDFActionPerformed

    private void exportVisuRelatorioVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportVisuRelatorioVendaActionPerformed

    }//GEN-LAST:event_exportVisuRelatorioVendaActionPerformed

    private void exportVisuVendasAgrupadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportVisuVendasAgrupadasActionPerformed

    }//GEN-LAST:event_exportVisuVendasAgrupadasActionPerformed

    private void exportVendasAgrupadasPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportVendasAgrupadasPDFActionPerformed

    }//GEN-LAST:event_exportVendasAgrupadasPDFActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void btnSelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelClienteActionPerformed
        op = openCliente(); 
        //idClient = controlVenda.selecionarId(selCli.tabClientes);
    }//GEN-LAST:event_btnSelClienteActionPerformed
    
    private void btnSelProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelProdActionPerformed
        idClient = controlVenda.selecionarId(selCli.tabClientes);
        if(idClient == -1){
            
            op = openCliente();
            //idClient = controlVenda.selecionarId(selCli.tabClientes);
            JOptionPane.showMessageDialog(selCli,"Selecione um cliente");
            //dispose();
        }else{
            openProduto();
            selProd.lblIdCli.setText(String.valueOf(controlVenda.selecionarId(selCli.tabClientes)));
            
        }/*if(idClient != -1){
            op = openProduto();
        }*/
        
        
        
    }//GEN-LAST:event_btnSelProdActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        if(op == 1){
           // idClient = controlVenda.selecionarId(selCli.tabClientes);
           idClient = controlVenda.selecionarId(selCli.tabClientes); 
           openProduto();
           selProd.lblIdCli.setText(String.valueOf(idClient));
            //idClient = controlVenda.selecionarId(selCli.tabClientes);
        }
        if(op == 2){
            idProd = controlVenda.selecionarId(selProd.tabProds);
            selProd.lblIdCli.setText(String.valueOf(idClient));
            qtd = (int) selProd.spinnerQtd.getValue();
            openCarrinho();
        }
        if(op == 3){
           carrinho.dispose();
        }
        if(idClient == -1 ){
            op = openCliente();
            JOptionPane.showMessageDialog(null, "Selecione um Cliente para prosseguir");
        }
       
        
        
        
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void btnAddCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarrinhoActionPerformed
        //item de venda
        if(selProd.isClosed()){
            btnAddCarrinho.setEnabled(false);
        }else{
            btnAddCarrinho.setEnabled(true);
            int x = (int) selProd.spinnerQtd.getValue();
            try {
                controlVenda.inserirItem(selProd.tabProds, x);
            } catch (IOException ex) {
                Logger.getLogger(CadastroVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
            selProd.tabCarrinho = controlVenda.atualizaTabela(selProd.tabCarrinho, colunas);
            selProd.lblRes.setText(String.valueOf(controlVenda.valorTotal(selProd.tabCarrinho)   ));
        }
        

    }//GEN-LAST:event_btnAddCarrinhoActionPerformed

    private void btnIrCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrCarrinhoActionPerformed
        /*
        selProd.dispose();
        op = openCarrinho();
        controlVenda.atualizaTabela();
        carrinho.lblres.setText(String.valueOf(controlVenda.valorTotal(carrinho.tabCarrinho)   ));
        */
    }//GEN-LAST:event_btnIrCarrinhoActionPerformed

    private void btnExcluirCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCarrinhoActionPerformed
        
        int posicao = selProd.tabCarrinho.getSelectedRow();
        //String y = (String)selProd.tabCarrinho.getValueAt(x,0);
        
        int itemvenda = controlVenda.selecionarId(selProd.tabCarrinho);
        //int idprod = (int) selProd.tabCarrinho.getValueAt(x,0);
        //int id = controlVenda.selecionarId(selProd.tabCarrinho);
        // int id = controlVenda.selecionarId(selProd.tabCarrinho);
        
        
        if(idvenda == -1){
            
            if(controlVenda.removerPosCarrinho(posicao) == true){
                selProd.tabCarrinho = controlVenda.atualizaTabela(selProd.tabCarrinho, colunas);
                selProd.lblRes.setText(String.valueOf(controlVenda.valorTotal(selProd.tabCarrinho)));
            }else{
                JOptionPane.showMessageDialog(null, "erro de exclusao");
            }
        }
        if(idvenda != -1){
            
            
            controlVenda.atualizarDados(idvenda);
            
            //System.out.println("nome "+y);
            if(controlVenda.removerPosCarrinho(itemvenda) == true ){
                selProd.tabCarrinho = controlVenda.atualizaTabela(selProd.tabCarrinho, colunas);
                selProd.lblRes.setText(String.valueOf(controlVenda.valorTotal(selProd.tabCarrinho)));
            }else {
                JOptionPane.showMessageDialog(null, "erro de exclusao");
            }
        }
        
        
        

        

    }//GEN-LAST:event_btnExcluirCarrinhoActionPerformed

    private void btnRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVendaActionPerformed
        
        
        if(config == true){
            if(controlVenda.deleteVenda(idvenda) == true){
                controlVenda.gravarItens(controlVenda.getItensVenda());
                controlVenda.novaVenda(true, idvenda, idClient, controlVenda.getItensVenda());
                controlVenda.setCont(cont);
                if(controlVenda.gravarVenda(controlVenda.getVenda()) == true){
                    JOptionPane.showMessageDialog(null, "Venda Alterada!");
                    dispose();
                }
            }
            
        }
        if(config == false){
            if(controlVenda.gravarItens(controlVenda.getItensVenda()) == true){
            
            }
        
            if(controlVenda.novaVenda(false, idvenda, idClient, controlVenda.getItensVenda())){
            //gravar itens
            controlVenda.setCont(cont);
                if(controlVenda.gravarVenda(controlVenda.getVenda()) == true){
                    JOptionPane.showMessageDialog(null, "Venda Registrada!");
                    dispose();
                }
            }
        }
        
        
        
    }//GEN-LAST:event_btnRegistrarVendaActionPerformed
    /*
    private void selProdbtnExcluirCarrinhoActionPerformed(java.awt.event.ActionEvent evt){
        
        int id = controlVenda.selecionarId(selProd.tabCarrinho);
        String [] colunas = new String[]{"ID ","NOME DO PRODUTO","DESCRIÇÃO","PREÇO", "QUANTIDADE","PREÇO TOTAL"};
       // int id = controlVenda.selecionarId(selProd.tabCarrinho);
       controlVenda.removerProdCarrinho(selProd.tabCarrinho, id);
       
       selProd.tabCarrinho = controlVenda.atualizaTabela(selProd.tabCarrinho, colunas);
       
    }
    */
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVenda(false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCarrinho;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnExcluirCarrinho;
    private javax.swing.JButton btnIrCarrinho;
    private javax.swing.JButton btnRegistrarVenda;
    private javax.swing.JButton btnSelCliente;
    private javax.swing.JButton btnSelProd;
    private javax.swing.JDesktopPane deskPane;
    private javax.swing.JMenuItem exportClientePDF;
    private javax.swing.JMenuItem exportMaioresClientes;
    private javax.swing.JMenuItem exportProdutoPDF;
    private javax.swing.JMenuItem exportVendasAgrupadasPDF;
    private javax.swing.JMenuItem exportVendasPDF;
    private javax.swing.JMenuItem exportVisuRelatorioClientes;
    private javax.swing.JMenuItem exportVisuRelatorioProdutos;
    private javax.swing.JMenuItem exportVisuRelatorioVenda;
    private javax.swing.JMenuItem exportVisuVendasAgrupadas;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenuItem menuClieCad;
    private javax.swing.JMenuItem menuCliePesq;
    private javax.swing.JMenuItem menuProdCad;
    private javax.swing.JMenuItem menuProdPesq;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuUser;
    private javax.swing.JMenuItem menuUserCad;
    private javax.swing.JMenuItem menuUserPesq;
    private javax.swing.JMenuItem menuVendCad;
    private javax.swing.JMenuItem menuVendPesq;
    private javax.swing.JMenu menuVenda;
    private javax.swing.JMenu relatorioMenuCliente;
    private javax.swing.JMenu relatorioMenuProduto;
    private javax.swing.JMenu relatorioMenuVenda;
    // End of variables declaration//GEN-END:variables
    
    
    public int openCliente(){
        deskPane.removeAll();
        selCli = new SelecionarCliente();
        
        deskPane.add(selCli).setVisible(true);
        return 1;
    }
    public int openProduto(){
        deskPane.removeAll();
        selProd = new SelecionarProduto();
        deskPane.add(selProd).setVisible(true);
        return 2;
    }
    public int openCarrinho(){
        deskPane.removeAll();
        carrinho = new Carrinho();
        deskPane.add(carrinho).setVisible(true);
        return 3;
    }
    
    public JTable uptabela(JTable tabCarrinho , int idVenda){
        
        tabCarrinho = controlVenda.dadostabela(tabCarrinho,controlVenda.buscarDadosAlterar( idVenda), colunas);
        
        return tabCarrinho;
    }
    
   
}
